server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: 'nijin'
    password: 'password'
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl_auto: update
    show_sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
